import type { Item } from './types';

export const servicesAndProducts: Item[] = [
  {
    id: 'home-1',
    category: 'home',
    subCategory: 'installation',
    type: 'service',
    name: { en: 'Washing Machine Installation', sv: 'Installation av tvättmaskin' },
    description: { en: 'Professional installation of all types of washing machines. We ensure proper plumbing and electrical connections.', sv: 'Professionell installation av alla typer av tvättmaskiner. Vi säkerställer korrekta VVS- och elanslutningar.' },
    longDescription: {
      en: 'Our certified technicians handle everything from unboxing and positioning your new washing machine to connecting all water inlets, drainage pipes, and electrical supplies. We perform a full cycle test to ensure there are no leaks and that the machine is operating perfectly. We can also uninstall and dispose of your old appliance for a small additional fee. This service is suitable for freestanding and integrated models.',
      sv: 'Våra certifierade tekniker hanterar allt från uppackning och placering av din nya tvättmaskin till anslutning av alla vatteninlopp, avloppsrör och elförsörjning. Vi utför ett komplett cykeltest för att säkerställer att det inte finns några läckor och att maskinen fungerar perfekt. Vi kan även avinstallera och avyttra din gamla apparat mot en liten extra avgift. Tjänsten passar för fristående och integrerade modeller.'
    },
    price: { sek: 800, pkr: 15000 },
    imageUrl: 'https://images.unsplash.com/photo-1626806819282-2c1dc01a5e0c?w=400&h=300&fit=crop&q=80',
    durationHours: 1.5,
    includes: {
        en: ['Unboxing and positioning', 'Water & drainage connection', 'Electrical supply connection', 'Full cycle test'],
        sv: ['Uppackning och positionering', 'Anslutning av vatten & avlopp', 'Anslutning av elförsörjning', 'Fullständigt cykeltest']
    },
  },
  {
    id: 'home-2',
    category: 'home',
    subCategory: 'repair',
    type: 'service',
    name: { en: 'Electrical Fixes', sv: 'El-reparationer' },
    description: { en: 'Certified electricians for all your home electrical needs, from fixing outlets to complete wiring.', sv: 'Certifierade elektriker för alla dina elbehov i hemmet, från att fixa uttag till komplett kabeldragning.' },
    price: { sek: 1200, pkr: 20000 },
    imageUrl: 'https://images.unsplash.com/photo-1517028152949-87321aa3a789?w=400&h=300&fit=crop&q=80',
  },
  {
    id: 'home-3',
    category: 'home',
    subCategory: 'renovation',
    type: 'service',
    name: { en: 'Kitchen Renovation', sv: 'Köksrenovering' },
    description: { en: 'Complete kitchen renovation and decor services. From design to execution, we build your dream kitchen.', sv: 'Kompletta köksrenoverings- och inredningstjänster. Från design till utförande bygger vi ditt drömkök.' },
    price: { sek: 50000, pkr: 1000000 },
    imageUrl: 'https://images.unsplash.com/photo-1556912173-3bb406ef7e77?w=400&h=300&fit=crop&q=80',
  },
  {
    id: 'home-4',
    category: 'home',
    type: 'product',
    name: { en: 'Smart LED Bulb Set', sv: 'Set med smarta LED-lampor' },
    description: { en: 'Energy-efficient smart LED bulbs. Controllable via your smartphone. Set includes 4 bulbs.', sv: 'Energieffektiva smarta LED-lampor. Styrbara via din smartphone. Setet innehåller 4 lampor.' },
    price: { sek: 600, pkr: 12000 },
    imageUrl: 'https://images.unsplash.com/photo-1588405215944-bf6394465a3d?w=400&h=300&fit=crop&q=80',
  },
  {
    id: 'home-5',
    category: 'home',
    subCategory: 'repair',
    type: 'service',
    name: { en: 'AC Installation & Repair', sv: 'AC-installation och reparation' },
    description: { en: 'Expert installation and repair for all types of air conditioning units. Stay cool all summer.', sv: 'Expertinstallation och reparation av alla typer av luftkonditioneringsenheter. Håll dig sval hela sommaren.' },
    price: { sek: 1500, pkr: 25000 },
    imageUrl: 'https://images.unsplash.com/photo-1574574937728-1a5fa4a43c2a?w=400&h=300&fit=crop&q=80',
  },
  {
    id: 'home-6',
    category: 'home',
    subCategory: 'installation',
    type: 'service',
    name: { en: 'Plumbing Services', sv: 'VVS-tjänster' },
    description: { en: 'From leaky faucets to clogged drains, our professional plumbers handle it all with efficiency and care.', sv: 'Från läckande kranar till igensatta avlopp, våra professionella rörmokare hanterar allt med effektivitet och omsorg.' },
    price: { sek: 1000, pkr: 18000 },
    imageUrl: 'https://images.unsplash.com/photo-1562886889-01420a711c9e?w=400&h=300&fit=crop&q=80',
  },
  {
    id: 'home-7',
    category: 'home',
    subCategory: 'cleaning',
    type: 'service',
    name: { en: 'Home Deep Cleaning', sv: 'Hemstädning (djuprengöring)' },
    description: { en: 'A thorough top-to-bottom cleaning of your entire home. We clean places you didn\'t even know were dirty.', sv: 'En grundlig rengöring av hela ditt hem från topp till botten. Vi städar platser du inte ens visste var smutsiga.' },
    price: { sek: 2500, pkr: 40000 },
    imageUrl: 'https://images.unsplash.com/photo-1585421514219-0734a7364bee?w=400&h=300&fit=crop&q=80',
  },
  {
    id: 'home-8',
    category: 'home',
    subCategory: 'installation',
    type: 'service',
    name: { en: 'Solar Panel Installation', sv: 'Installation av solpaneler' },
    description: { en: 'Go green and save on energy bills with our professional solar panel installation services for your home.', sv: 'Bli grön och spara på energiräkningarna med våra professionella installationstjänster för solpaneler till ditt hem.' },
    price: { sek: 75000, pkr: 1500000 },
    imageUrl: 'https://images.unsplash.com/photo-1508515053969-7b94594e62c1?w=400&h=300&fit=crop&q=80',
  },
  {
    id: 'home-9',
    category: 'home',
    subCategory: 'cleaning',
    type: 'service',
    name: { en: 'Pest Control Service', sv: 'Skadedjursbekämpning' },
    description: { en: 'Effective and safe pest control solutions to protect your home from unwanted insects and rodents.', sv: 'Effektiva och säkra skadedjursbekämpningslösningar för att skydda ditt hem från oönskade insekter och gnagare.' },
    price: { sek: 1800, pkr: 30000 },
    imageUrl: 'https://images.unsplash.com/photo-1605501865158-372935a8813a?w=400&h=300&fit=crop&q=80',
  },
  {
    id: 'home-10',
    category: 'home',
    type: 'product',
    name: { en: 'Home Security Camera Set', sv: 'Säkerhetskamera-set för hemmet' },
    description: { en: 'A set of 4 high-definition wireless security cameras to monitor your home 24/7 from your phone.', sv: 'Ett set med 4 högupplösta trådlösa säkerhetskameror för att övervaka ditt hem dygnet runt från din telefon.' },
    price: { sek: 3000, pkr: 50000 },
    imageUrl: 'https://images.unsplash.com/photo-1589935447037-124318c0df11?w=400&h=300&fit=crop&q=80',
  },
  {
    id: 'home-11',
    category: 'home',
    subCategory: 'demolition',
    type: 'service',
    name: { en: 'Demolition Service', sv: 'Rivningstjänst' },
    description: { en: 'Safe and efficient demolition for interior walls, small structures, and site clearing.', sv: 'Säker och effektiv rivning av innerväggar, mindre strukturer och röjning.' },
    price: { sek: 10000, pkr: 200000 },
    imageUrl: 'https://images.unsplash.com/photo-1542847668-3d4054203799?w=400&h=300&fit=crop&q=80',
  },
  {
    id: 'home-12',
    category: 'home',
    subCategory: 'moving',
    type: 'service',
    name: { en: 'Full Moving Service', sv: 'Komplett Flytthjälp' },
    description: { en: 'Comprehensive moving assistance, including packing, transport, and unpacking at your new home.', sv: 'Omfattande flytthjälp, inklusive packning, transport och uppackning i ditt nya hem.' },
    price: { sek: 8000, pkr: 150000 },
    imageUrl: 'https://images.unsplash.com/photo-1587589396349-99238f219934?w=400&h=300&fit=crop&q=80',
  },
  {
    id: 'home-13',
    category: 'home',
    subCategory: 'repair',
    type: 'service',
    name: { en: 'Appliance Repair', sv: 'Reparation av vitvaror' },
    description: { en: 'Expert repair for refrigerators, ovens, dishwashers, and more. Fast and reliable service.', sv: 'Expertmässig reparation av kylskåp, ugnar, diskmaskiner med mera. Snabb och pålitlig service.' },
    price: { sek: 950, pkr: 17000 },
    imageUrl: 'https://images.unsplash.com/photo-1578894060232-235a3396513b?w=400&h=300&fit=crop&q=80',
    durationHours: 1.5,
    includes: {
        en: ['Diagnostic check', 'Labor for repair', '90-day warranty on work'],
        sv: ['Diagnostisk kontroll', 'Arbetskostnad för reparation', '90 dagars garanti på arbetet']
    },
  },
  {
    id: 'home-14',
    category: 'home',
    subCategory: 'catering',
    type: 'service',
    name: { en: 'Event Catering (per person)', sv: 'Eventcatering (per person)' },
    description: { en: 'Delicious catering for your private events, parties, or corporate meetings. Customizable menus.', sv: 'Utsökt catering för dina privata evenemang, fester eller företagsmöten. Anpassningsbara menyer.' },
    price: { sek: 450, pkr: 8000 },
    imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400&h=300&fit=crop&q=80',
  },
  {
    id: 'home-15',
    category: 'home',
    subCategory: 'wellness',
    type: 'service',
    name: { en: 'Personal Training Session', sv: 'Personlig Träningssession' },
    description: { en: 'One-on-one personal training session with a certified coach, at your home or a designated location.', sv: 'En-mot-en personlig träningssession med en certifierad coach, hemma hos dig eller på en angiven plats.' },
    price: { sek: 700, pkr: 12000 },
    imageUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=300&fit=crop&q=80',
  },
  {
    id: 'home-16',
    category: 'home',
    subCategory: 'pet',
    type: 'service',
    name: { en: 'Pet Grooming', sv: 'Husdjursskötsel' },
    description: { en: 'Professional grooming for your furry friends. Includes bath, haircut, and nail trimming.', sv: 'Professionell pälsvård för dina lurviga vänner. Inkluderar bad, klippning och kloklippning.' },
    price: { sek: 600, pkr: 10000 },
    imageUrl: 'https://images.unsplash.com/photo-1597799191630-f04c16a18eda?w=400&h=300&fit=crop&q=80',
  },
  {
    id: 'home-17',
    category: 'home',
    subCategory: 'education',
    type: 'service',
    name: { en: 'Private Tutoring (per hour)', sv: 'Privatlektion (per timme)' },
    description: { en: 'Personalized tutoring sessions for various subjects and levels, from primary school to university.', sv: 'Personliga handledningssessioner för olika ämnen och nivåer, från grundskola till universitet.' },
    price: { sek: 500, pkr: 9000 },
    imageUrl: 'https://images.unsplash.com/photo-1588580264936-35d1c3a6e9a3?w=400&h=300&fit=crop&q=80',
  },
  {
    id: 'home-18',
    category: 'home',
    subCategory: 'flooring',
    type: 'service',
    name: { en: 'Hardwood Flooring Installation', sv: 'Installation av trägolv' },
    description: { en: 'Professional installation of hardwood, laminate, or vinyl flooring. Price per square meter.', sv: 'Professionell läggning av parkett-, laminat- eller vinylgolv. Pris per kvadratmeter.' },
    price: { sek: 500, pkr: 9000 },
    imageUrl: 'https://images.unsplash.com/photo-1599696848652-f5ff418e8d83?w=400&h=300&fit=crop&q=80',
  },
  {
    id: 'home-19',
    category: 'home',
    subCategory: 'construction',
    type: 'service',
    name: { en: 'Deck & Patio Construction', sv: 'Bygge av altan & uteplats' },
    description: { en: 'Design and construction of custom decks and patios to enhance your outdoor living space.', sv: 'Design och bygge av skräddarsydda altaner och uteplatser för att förbättra ditt utomhusliv.' },
    price: { sek: 45000, pkr: 850000 },
    imageUrl: 'https://images.unsplash.com/photo-1566763914525-2e621111005b?w=400&h=300&fit=crop&q=80',
  },
  {
    id: 'home-20',
    category: 'home',
    subCategory: 'renovation',
    type: 'service',
    name: { en: 'Complete Bathroom Renovation', sv: 'Komplett badrumsrenovering' },
    description: { en: 'Full-service bathroom remodeling, from design and waterproofing to tiling and fixture installation.', sv: 'Helhetslösning för badrumsrenovering, från design och tätskikt till kakling och installation av inredning.' },
    price: { sek: 80000, pkr: 1600000 },
    imageUrl: 'https://images.unsplash.com/photo-1600585153313-62a63b9658b1?w=400&h=300&fit=crop&q=80',
  },
  {
    id: 'car-1',
    category: 'car',
    subCategory: 'maintenance',
    type: 'service',
    name: { en: 'Tire Change', sv: 'Däckbyte' },
    description: { en: 'Seasonal tire change service. We swap your summer/winter tires quickly and safely.', sv: 'Säsongsbetonad däckbytesservice. Vi byter dina sommar-/vinterdäck snabbt och säkert.' },
    price: { sek: 500, pkr: 8000 },
    imageUrl: 'https://images.unsplash.com/photo-1599442131971-f3f224977931?w=400&h=300&fit=crop&q=80',
  },
  {
    id: 'car-2',
    category: 'car',
    subCategory: 'maintenance',
    type: 'service',
    name: { en: 'Full Car Wash', sv: 'Helbiltvätt' },
    description: { en: 'Premium car wash service including interior and exterior cleaning, waxing, and polishing.', sv: 'Premium biltvättservice inklusive invändig och utvändig rengörring, vaxning och polering.' },
    price: { sek: 400, pkr: 7000 },
    imageUrl: 'https://images.unsplash.com/photo-1603584839810-9a27b61e27a7?w=400&h=300&fit=crop&q=80',
  },
  {
    id: 'car-3',
    category: 'car',
    subCategory: 'inspection',
    type: 'service',
    name: { en: 'Car Inspection', sv: 'Bilinspektion' },
    description: { en: 'Comprehensive vehicle inspection covering all major systems to ensure your car is in top condition.', sv: 'Omfattande fordonsinspektion som täcker alla större system för att säkerställa att din bil är i toppskick.' },
    price: { sek: 900, pkr: 16000 },
    imageUrl: 'https://images.unsplash.com/photo-1571201506264-a6b996144b23?w=400&h=300&fit=crop&q=80',
  },
  {
    id: 'car-4',
    category: 'car',
    type: 'product',
    name: { en: 'Premium Car Cover', sv: 'Premium bilskydd' },
    description: { en: 'All-weather, waterproof and breathable car cover to protect your vehicle from the elements.', sv: 'Vattentätt och andningsbart bilskydd för alla väder för att skydda ditt fordon från väder och vind.' },
    price: { sek: 750, pkr: 14000 },
    imageUrl: 'https://images.unsplash.com/photo-1616422285421-f3575354972a?w=400&h=300&fit=crop&q=80',
  },
  {
    id: 'car-5',
    category: 'car',
    subCategory: 'maintenance',
    type: 'service',
    name: { en: 'Car Detailing', sv: 'Bilrekonditionering' },
    description: { en: 'Meticulous interior and exterior detailing to restore your car\'s showroom shine. Includes clay bar, polish, and wax.', sv: 'Noggrann invändig och utvändig rekonditionering för att återställa din bils utställningsglans. Inkluderar lerbehandling, polering och vax.' },
    longDescription: {
      en: 'Our full car detailing package is a comprehensive cleaning and reconditioning of your vehicle. The exterior treatment includes a multi-stage wash, chemical decontamination to remove tar and iron deposits, clay bar treatment to smooth the paint, a single-stage machine polish to enhance gloss, and a high-quality carnauba wax or sealant for protection. The interior is vacuumed, carpets and upholstery are shampooed, and all surfaces (dashboard, door panels, console) are cleaned and conditioned.',
      sv: 'Vårt kompletta bilrekonditioneringspaket är en omfattande rengöring och återställning av ditt fordon. Exteriörbehandlingen inkluderar en flerstegstvätt, kemisk dekontaminering för att avlägsna tjära och järnpartiklar, lerbehandling för att jämna ut lacken, en enstegs maskinpolering för att öka glansen och ett högkvalitativt karnaubavax eller tätningsmedel för skydd. Interiören dammsugs, mattor och klädsel schamponeras, och alla ytor (instrumentbräda, dörrpaneler, konsol) rengörs och behandlas.'
    },
    price: { sek: 2000, pkr: 35000 },
    imageUrl: 'https://images.unsplash.com/photo-1551522435-a131bf538a72?w=400&h=300&fit=crop&q=80',
    durationHours: 4,
    includes: {
        en: ['Multi-stage wash', 'Chemical decontamination', 'Clay bar treatment', 'Single-stage machine polish', 'High-quality wax or sealant', 'Interior shampoo & conditioning'],
        sv: ['Flerstegstvätt', 'Kemisk dekontaminering', 'Lerbehandling', 'Enstegs maskinpolering', 'Högkvalitativt vax eller lackskydd', 'Invändig schamponering & behandling']
    },
  },
  {
    id: 'car-6',
    category: 'car',
    subCategory: 'maintenance',
    type: 'service',
    name: { en: 'Oil Change Service', sv: 'Oljebytesservice' },
    description: { en: 'Quick and professional engine oil and filter change to keep your car running smoothly. Includes fluid top-up.', sv: 'Snabbt och professionellt byte av motorolja och filter för att hålla din bil igång smidigt. Inkluderar påfyllning av vätskor.' },
    price: { sek: 800, pkr: 14000 },
    imageUrl: 'https://images.unsplash.com/photo-1622053641243-2c13d7b32f2e?w=400&h=300&fit=crop&q=80',
  },
  {
    id: 'car-7',
    category: 'car',
    subCategory: 'repair',
    type: 'service',
    name: { en: 'Brake Repair Service', sv: 'Bromsreparation' },
    description: { en: 'Complete brake system check and repair, including pads, rotors, and fluid replacement for your safety.', sv: 'Komplett kontroll och reparation av bromssystemet, inklusive belägg, skivor och vätskebyte för din säkerhet.' },
    price: { sek: 2500, pkr: 45000 },
    imageUrl: 'https://images.unsplash.com/photo-1591761922434-3f2d22b64a6a?w=400&h=300&fit=crop&q=80',
  },
  {
    id: 'car-8',
    category: 'car',
    subCategory: 'repair',
    type: 'service',
    name: { en: 'Car Battery Replacement', sv: 'Byte av bilbatteri' },
    description: { en: 'Reliable car battery testing and replacement service to ensure you never get stranded.', sv: 'Pålitlig testning och byte av bilbatteri för att säkerställa att du aldrig blir strandsatt.' },
    price: { sek: 1800, pkr: 30000 },
    imageUrl: 'https://images.unsplash.com/photo-1620836259747-d399c751a02e?w=400&h=300&fit=crop&q=80',
  },
  {
    id: 'car-9',
    category: 'car',
    subCategory: 'repair',
    type: 'service',
    name: { en: 'Windshield Chip Repair', sv: 'Reparation av stenskott' },
    description: { en: 'Quickly repair chips and cracks in your windshield to prevent them from spreading and restore visibility.', sv: 'Reparera snabbt stenskott och sprickor i din vindruta för att förhindra att de sprider sig och återställa sikten.' },
    price: { sek: 700, pkr: 12000 },
    imageUrl: 'https://images.unsplash.com/photo-1629452296136-1e0e45136a6e?w=400&h=300&fit=crop&q=80',
  },
  {
    id: 'car-10',
    category: 'car',
    type: 'product',
    name: { en: 'Car GPS Tracker', sv: 'GPS-spårare för bil' },
    description: { en: 'Real-time GPS tracker for your car. Monitor location, speed, and get theft alerts on your smartphone.', sv: 'Realtids GPS-spårare för din bil. Övervaka position, hastighet och få stöldlarm på din smartphone.' },
    price: { sek: 900, pkr: 16000 },
    imageUrl: 'https://images.unsplash.com/photo-1589558833932-488b0a1a5b82?w=400&h=300&fit=crop&q=80',
  },
  {
    id: 'car-11',
    category: 'car',
    type: 'service',
    name: { en: 'Car Share (per hour)', sv: 'Bilpool (per timme)' },
    description: { en: 'Rent a car by the hour. Perfect for quick trips and errands. Fuel and insurance included.', sv: 'Hyr en bil per timme. Perfekt för snabba resor och ärenden. Bränsle och försäkring ingår.' },
    price: { sek: 150, pkr: 2500 },
    imageUrl: 'https://images.unsplash.com/photo-1617469747334-0a3735a49a9b?w=400&h=300&fit=crop&q=80',
  },
  {
    id: 'bike-1',
    category: 'bike',
    type: 'service',
    name: { en: 'Cargo Bike Rental', sv: 'Hyr Lastcykel' },
    description: { en: 'Rent a sturdy cargo bike for your moving or transportation needs. Perfect for heavy loads in the city.', sv: 'Hyr en robust lastcykel för dina flytt- eller transportbehov. Perfekt för tunga laster i staden.' },
    price: { sek: 300, pkr: 5000 },
    imageUrl: 'https://images.unsplash.com/photo-1622287823547-4a0558b23a9d?w=400&h=300&fit=crop&q=80',
  },
  {
    id: 'bike-2',
    category: 'bike',
    type: 'service',
    name: { en: 'Electric Bike Rental', sv: 'Hyr Elcykel' },
    description: { en: 'Explore the city with ease. Our electric bikes make commuting and sightseeing a breeze.', sv: 'Utforska staden med lätthet. Våra elcyklar gör pendling och sightseeing till en barnlek.' },
    price: { sek: 250, pkr: 4500 },
    imageUrl: 'https://images.unsplash.com/photo-1576222773413-332a69c824c2?w=400&h=300&fit=crop&q=80',
  },
  {
    id: 'bike-3',
    category: 'bike',
    type: 'service',
    name: { en: 'City Bike Rental', sv: 'Hyr Stadscykel' },
    description: { en: 'Classic and reliable city bikes for your daily travels. Includes helmet and lock.', sv: 'Klassiska och pålitliga stadscyklar för dina dagliga resor. Inkluderar hjälm och lås.' },
    price: { sek: 150, pkr: 2500 },
    imageUrl: 'https://images.unsplash.com/photo-1559348331-57d6863035f2?w=400&h=300&fit=crop&q=80',
  },
  {
    id: 'bike-4',
    category: 'bike',
    type: 'service',
    name: { en: 'Tandem Bike Rental', sv: 'Hyr Tandemcykel' },
    description: { en: 'Double the fun! Rent a tandem bike for two. Great for a day out with a friend or partner.', sv: 'Dubbelt så roligt! Hyr en tandemcykel för två. Perfekt för en utflyktsdag med en vän eller partner.' },
    price: { sek: 200, pkr: 3500 },
    imageUrl: 'https://images.unsplash.com/photo-1594736135327-3b851b228151?w=400&h=300&fit=crop&q=80',
  },
  {
    id: 'storage-1',
    category: 'storage',
    type: 'service',
    name: { en: 'Moving Box Rental (10 pack)', sv: 'Hyra flyttlådor (10-pack)' },
    description: { en: 'Rent a pack of 10 sturdy, reusable moving boxes. Delivered to your door and picked up when you\'re done.', sv: 'Hyr ett 10-pack med robusta, återanvändbara flyttlådor. Levereras till din dörr och hämtas när du är klar.' },
    price: { sek: 200, pkr: 3500 },
    imageUrl: 'https://images.unsplash.com/photo-1566576721346-d4a3b4eaeb55?w=400&h=300&fit=crop&q=80',
  },
  {
    id: 'storage-2',
    category: 'storage',
    type: 'service',
    name: { en: 'Small Storage Unit (2 sqm)', sv: 'Litet förråd (2 kvm)' },
    description: { en: 'Secure, clean, and dry storage unit. Perfect for storing seasonal items or boxes. 24/7 access.', sv: 'Säkert, rent och torrt förråd. Perfekt för förvaring av säsongsbetonade föremål eller lådor. Tillgång dygnet runt.' },
    price: { sek: 800, pkr: 15000 },
    imageUrl: 'https://images.unsplash.com/photo-1622224029643-8015306e8281?w=400&h=300&fit=crop&q=80',
  },
  {
    id: 'storage-3',
    category: 'storage',
    type: 'service',
    name: { en: 'Wardrobe Box Rental', sv: 'Hyra garderobslåda' },
    description: { en: 'Keep your clothes wrinkle-free during your move. Sturdy wardrobe boxes with a metal hanging bar.', sv: 'Håll dina kläder skrynkelfria under flytten. Robusta garderobslådor med en hängstång i metall.' },
    price: { sek: 100, pkr: 1800 },
    imageUrl: 'https://images.unsplash.com/photo-1576579220288-7a54a01a4175?w=400&h=300&fit=crop&q=80',
  },
  {
    id: 'storage-4',
    category: 'storage',
    type: 'service',
    name: { en: 'Parcel Locker (Monthly)', sv: 'Paketbox (Månadsvis)' },
    description: { en: 'Securely receive packages 24/7 with your personal parcel locker. Monthly subscription.', sv: 'Ta emot paket säkert dygnet runt med din personliga paketbox. Månadsprenumeration.' },
    price: { sek: 99, pkr: 1800 },
    imageUrl: 'https://images.unsplash.com/photo-1585773663141-50f232938b81?w=400&h=300&fit=crop&q=80',
  },
  {
    id: 'storage-5',
    category: 'storage',
    type: 'service',
    name: { en: 'Climate Controlled Storage (5 sqm)', sv: 'Klimatkontrollerat förråd (5 kvm)' },
    description: { en: 'Protect your sensitive belongings like electronics, art, or furniture in our climate-controlled units.', sv: 'Skydda dina känsliga tillhörigheter som elektronik, konst eller möbler i våra klimatkontrollerade förråd.' },
    price: { sek: 1500, pkr: 25000 },
    imageUrl: 'https://images.unsplash.com/photo-1590130386928-1b26da4296f0?w=400&h=300&fit=crop&q=80',
  },
  {
    id: 'pickup-1',
    category: 'pickup',
    type: 'service',
    name: { en: 'Pickup & Drop-off Service', sv: 'Hämta & Lämna-service' },
    description: { en: 'We pick up your items and deliver them to your desired location within the city. Fast and reliable.', sv: 'Vi hämtar dina saker och levererar dem till önskad plats inom staden. Snabbt och pålitligt.' },
    price: { sek: 150, pkr: 2500 },
    imageUrl: 'https://images.unsplash.com/photo-1591802252429-04473b15f9b4?w=400&h=300&fit=crop&q=80',
  },
  {
    id: 'storage-6',
    category: 'storage',
    type: 'service',
    name: { en: 'Power Drill Rental (24h)', sv: 'Hyr Borrmaskin (24h)' },
    description: { en: 'Rent a powerful cordless drill for your DIY projects. Includes battery, charger, and a set of bits.', sv: 'Hyr en kraftfull sladdlös borrmaskin för dina gör-det-själv-projekt. Inkluderar batteri, laddare och ett set med borr.' },
    price: { sek: 250, pkr: 4500 },
    imageUrl: 'https://images.unsplash.com/photo-1621431210398-c847a1670987?w=400&h=300&fit=crop&q=80',
  },
  {
    id: 'storage-7',
    category: 'storage',
    type: 'service',
    name: { en: 'Party Tent Rental (4x8m)', sv: 'Hyr Partytält (4x8m)' },
    description: { en: 'Rent a spacious and durable party tent for your event. Easy to set up. Perfect for up to 40 guests.', sv: 'Hyr ett rymligt och tåligt partytält för ditt evenemang. Lätt att sätta upp. Perfekt för upp till 40 gäster.' },
    price: { sek: 1800, pkr: 30000 },
    imageUrl: 'https://images.unsplash.com/photo-1568498831110-38375433d7b0?w=400&h=300&fit=crop&q=80',
  },
  {
    id: 'vending-1',
    category: 'vending',
    type: 'service',
    name: { en: 'Office Coffee Machine', sv: 'Kaffemaskin för kontor' },
    description: { en: 'Monthly rental of a premium coffee machine for your office. Includes service and refills.', sv: 'Månadshyra av en premium kaffemaskin till ert kontor. Inkluderar service och påfyllning.' },
    price: { sek: 2500, pkr: 45000 },
    imageUrl: 'https://images.unsplash.com/photo-1559305439-327589071295?w=400&h=300&fit=crop&q=80',
  },
  {
    id: 'parking-1',
    category: 'parking',
    type: 'service',
    name: { en: 'Private Parking Spot (Monthly)', sv: 'Privat P-plats (Månad)' },
    description: { en: 'Rent a secure and private parking spot in a central location. 24/7 access.', sv: 'Hyr en säker och privat parkeringsplats centralt. Tillgång dygnet runt.' },
    price: { sek: 1200, pkr: 20000 },
    imageUrl: 'https://images.unsplash.com/photo-1572318823855-65b19815a133?w=400&h=300&fit=crop&q=80',
  },
  {
    id: 'vending-2',
    category: 'vending',
    type: 'service',
    name: { en: 'Snack & Drink Vending Machine', sv: 'Snacks- och dryckesautomat' },
    description: { en: 'Monthly rental of a combo vending machine for snacks and cold drinks. We keep it stocked with popular brands.', sv: 'Månadshyra av en kombiautomat för snacks och kalla drycker. Vi håller den fylld med populära märken.' },
    price: { sek: 2000, pkr: 38000 },
    imageUrl: 'https://images.unsplash.com/photo-1585060141663-3932845c0551?w=400&h=300&fit=crop&q=80',
  },
  {
    id: 'parking-2',
    category: 'parking',
    type: 'service',
    name: { en: 'Secure Garage Spot (Monthly)', sv: 'Säker Garageplats (Månad)' },
    description: { en: 'A spot in a heated and monitored underground garage. Protect your car from weather and theft.', sv: 'En plats i ett uppvärmt och övervakat underjordiskt garage. Skydda din bil från väder och stöld.' },
    price: { sek: 2000, pkr: 35000 },
    imageUrl: 'https://images.unsplash.com/photo-1523987355523-c745e5d12549?w=400&h=300&fit=crop&q=80',
  },
  {
    id: 'vending-3',
    category: 'vending',
    type: 'service',
    name: { en: 'Healthy Snack Vending Machine', sv: 'Automat för hälsosamma snacks' },
    description: { en: 'Offer healthy options like granola bars, dried fruit, and nuts. We stock it with organic and low-sugar choices.', sv: 'Erbjud hälsosamma alternativ som granolabars, torkad frukt och nötter. Vi fyller den med ekologiska och sockerfria val.' },
    price: { sek: 2200, pkr: 42000 },
    imageUrl: 'https://images.unsplash.com/photo-1615485925348-3c415d22f281?w=400&h=300&fit=crop&q=80',
  },
  {
    id: 'handyman-1',
    category: 'handyman',
    subCategory: 'small-repairs',
    type: 'service',
    name: { en: 'Small Household Repairs', sv: 'Mindre hushållsreparationer' },
    description: { en: 'Quick and reliable fixes for leaky faucets, sticky doors, broken tiles, and other small jobs around the house.', sv: 'Snabba och pålitliga lösningar för läckande kranar, kärvande dörrar, trasiga kakelplattor och andra småjobb i hemmet.' },
    price: { sek: 650, pkr: 11000 },
    imageUrl: 'https://images.unsplash.com/photo-1593352219758-c2885f25752a?w=400&h=300&fit=crop&q=80',
  },
  {
    id: 'handyman-2',
    category: 'handyman',
    subCategory: 'assembly',
    type: 'service',
    name: { en: 'Furniture Assembly', sv: 'Möbelmontering' },
    description: { en: 'Professional assembly of flat-pack furniture from IKEA, Wayfair, and more. Save yourself the headache.', sv: 'Professionell montering av platta paket från IKEA, Wayfair med flera. Spara dig själv huvudvärken.' },
    price: { sek: 800, pkr: 15000 },
    imageUrl: 'https://images.unsplash.com/photo-1634505371809-51f016f3c2e6?w=400&h=300&fit=crop&q=80',
  },
  {
    id: 'handyman-3',
    category: 'handyman',
    subCategory: 'painting',
    type: 'service',
    name: { en: 'Interior Painting (One Room)', sv: 'Interiörmålning (ett rum)' },
    description: { en: 'Refresh the look of any room with a professional paint job. Includes prep work and clean-up for one standard-sized room.', sv: 'Fräscha upp utseendet på vilket rum som helst med en professionell målning. Inkluderar förarbete och städning för ett normalstort rum.' },
    price: { sek: 4500, pkr: 80000 },
    imageUrl: 'https://images.unsplash.com/photo-1600185966380-329a4a7538b7?w=400&h=300&fit=crop&q=80',
  },
  {
    id: 'handyman-4',
    category: 'handyman',
    subCategory: 'carpentry',
    type: 'service',
    name: { en: 'Custom Carpentry', sv: 'Snickeriarbeten' },
    description: { en: 'Custom shelves, built-in storage, trim work, and other small to medium carpentry projects.', sv: 'Skräddarsydda hyllor, inbyggd förvaring, lister och andra små till medelstora snickeriprojekt.' },
    price: { sek: 1500, pkr: 28000 },
    imageUrl: 'https://images.unsplash.com/photo-1593528498226-5b91b947c699?w=400&h=300&fit=crop&q=80',
  },
];

export const translations = {
  en: {
    title: 'Buzz',
    homeServices: 'Home Services',
    carServices: 'Car Services',
    rentalServices: 'Rental Services',
    hamtaServices: 'Pickup Services',
    vendingServices: 'Vending',
    parkingServices: 'Parking',
    handymanServices: 'Handyman',
    addToCart: 'Add to Cart',
    addedToCart: 'Added!',
    cartTitle: 'Your Cart',
    cartEmpty: 'Your cart is empty.',
    subtotal: 'Subtotal',
    checkout: 'Checkout',
    bookingDateTime: 'Booking Details',
    selectDateTime: 'Please select a date and time for the service',
    close: 'Close',
    language: 'Language',
    location: 'Location',
    english: 'English',
    swedish: 'Swedish',
    sweden: 'Sweden (SEK)',
    pakistan: 'Pakistan (PKR)',
    searchPlaceholder: 'Search for services...',
    footerText: 'All rights reserved.',
    contactUs: 'Contact Us',
    address: 'Address',
    viewDetails: 'View Details',
    hideDetails: 'Hide Details',
    viewMoreDetails: 'View More Details',
    hideMoreDetails: 'Hide More Details',
    orderSuccessTitle: 'Order Placed!',
    orderSuccessMessage: 'Thank you for your order. Your order ID is',
    backToShopping: 'Back to Shopping',
    paymentMethod: 'Payment Method',
    cashOnDelivery: 'Cash on Delivery',
    swish: 'Swish',
    card: 'Credit/Debit Card',
    googlePay: 'Google Pay',
    applePay: 'Apple Pay',
    placeOrder: 'Place Order',
    continueToPayment: 'Continue to Payment',
    backToCart: 'Back to Cart',
    deliveryAddress: 'Delivery Address',
    paymentDetails: 'Payment Details',
    orderSummary: 'Order Summary',
    heroTitle: 'Your Go-To for Home & Car Services',
    heroSubtitle: 'Reliable, professional services at your fingertips. Book now!',
    browseServices: 'Browse Services',
    item: 'item',
    items: 'items',
    ariaLabelLanguage: 'Select language',
    ariaLabelLocation: 'Select location',
    ariaLabelToggleDark: 'Switch to dark theme',
    ariaLabelToggleLight: 'Switch to light theme',
    ariaLabelOpenCart: 'Open cart',
    ariaLabelHomepage: 'Go to homepage',
    categories: 'Service categories',
    sort: 'Sort by',
    priceAsc: 'Price: Low to High',
    priceDesc: 'Price: High to Low',
    nameAsc: 'Name: A-Z',
    nameDesc: 'Name: Z-A',
    priceRange: 'Price Range',
    under: 'Under',
    over: 'Over',
    quickPay: 'Quick Pay',
    renovation: 'Renovation',
    installation: 'Installation',
    demolition: 'Demolition',
    cleaning: 'Cleaning',
    moving: 'Moving',
    homeServiceSubcategories: 'Home Service Type',
    carInspection: 'Inspection',
    carRepair: 'Repair',
    carMaintenance: 'Maintenance',
    carServiceSubcategories: 'Car Service Type',
    homeRepair: 'Repair',
    catering: 'Catering',
    wellness: 'Wellness',
    petServices: 'Pet Services',
    education: 'Education',
    handymanServiceSubcategories: 'Handyman Service Type',
    handymanSmallRepairs: 'Small Repairs',
    handymanAssembly: 'Assembly',
    handymanPainting: 'Painting',
    selectTimeFor: 'Select time for',
    noSlotsAvailable: 'No more slots available for today.',
    slotSelected: 'Slot selected!',
    fullName: 'Full Name',
    email: 'Email Address',
    phone: 'Phone Number',
    street: 'Street',
    city: 'City',
    postalCode: 'Postal Code',
    country: 'Country',
    cardholderName: 'Cardholder Name',
    cardNumber: 'Card Number',
    expiryDate: 'Expiry Date (MM/YY)',
    cvc: 'CVC',
    fieldRequired: 'This field is required',
    emailInvalid: 'Please enter a valid email address',
    phoneInvalid: 'Please enter a valid phone number',
    contactInfo: 'Contact Information',
    stepCart: 'Cart',
    stepDelivery: 'Delivery',
    stepPayment: 'Payment',
    stepConfirmation: 'Confirmation',
    showOrderSummary: 'Show Order Summary',
    hideOrderSummary: 'Hide Order Summary',
    flooring: 'Flooring',
    construction: 'Construction',
    carpentry: 'Carpentry',
    countrySweden: 'Sweden',
    countryPakistan: 'Pakistan',
    selectCountry: 'Select a country...',
    whatsIncluded: "What's Included",
    duration: "Duration",
    hours: "hours",
    'I agree to the': 'I agree to the',
    'Terms & Conditions': 'Terms & Conditions',
    termsContent: 'Terms and Conditions: These are placeholder terms. In a real application, this would link to a dedicated terms page.',
    'Pay Amount': 'Pay {amount}',
    scanWithSwish: 'Scan with Swish app',
    swishNumber: 'Swish Number',
    amountToPay: 'Amount to Pay',
  },
  sv: {
    title: 'Buzz',
    homeServices: 'Hemmatjänster',
    carServices: 'Biltjänster',
    rentalServices: 'Uthyrning',
    hamtaServices: 'Hämta-tjänster',
    vendingServices: 'Automater',
    parkingServices: 'Parkering',
    handymanServices: 'Hantverkare',
    addToCart: 'Lägg i varukorg',
    addedToCart: 'Tillagd!',
    cartTitle: 'Din varukorg',
    cartEmpty: 'Din varukorg är tom.',
    subtotal: 'Delsumma',
    checkout: 'Gå till kassan',
    bookingDateTime: 'Bokningsdetaljer',
    selectDateTime: 'Välj ett datum och en tid för tjänsten',
    close: 'Stäng',
    language: 'Språk',
    location: 'Plats',
    english: 'Engelska',
    swedish: 'Svenska',
    sweden: 'Sverige (SEK)',
    pakistan: 'Pakistan (PKR)',
    searchPlaceholder: 'Sök efter tjänster...',
    footerText: 'Alla rättigheter förbehållna.',
    contactUs: 'Kontakta oss',
    address: 'Adress',
    viewDetails: 'Visa detaljer',
    hideDetails: 'Dölj detaljer',
    viewMoreDetails: 'Visa mer information',
    hideMoreDetails: 'Dölj mer information',
    orderSuccessTitle: 'Beställning slutförd!',
    orderSuccessMessage: 'Tack för din beställning. Ditt order-ID är',
    backToShopping: 'Tillbaka till shopping',
    paymentMethod: 'Betalningsmetod',
    cashOnDelivery: 'Postförskott',
    swish: 'Swish',
    card: 'Kredit-/betalkort',
    googlePay: 'Google Pay',
    applePay: 'Apple Pay',
    placeOrder: 'Slutför beställning',
    continueToPayment: 'Fortsätt till betalning',
    backToCart: 'Tillbaka till varukorgen',
    deliveryAddress: 'Leveransadress',
    paymentDetails: 'Betalningsinformation',
    orderSummary: 'Ordersammanfattning',
    heroTitle: 'Ditt förstahandsval för hem- & biltjänster',
    heroSubtitle: 'Pålitliga, professionella tjänster nära till hands. Boka nu!',
    browseServices: 'Visa tjänster',
    item: 'artikel',
    items: 'artiklar',
    ariaLabelLanguage: 'Välj språk',
    ariaLabelLocation: 'Välj plats',
    ariaLabelToggleDark: 'Byt till mörkt tema',
    ariaLabelToggleLight: 'Byt till ljust tema',
    ariaLabelOpenCart: 'Öppna varukorg',
    ariaLabelHomepage: 'Gå till startsidan',
    categories: 'Tjänstekategorier',
    sort: 'Sortera efter',
    priceAsc: 'Pris: Lågt till Högt',
    priceDesc: 'Pris: Högt till Lågt',
    nameAsc: 'Namn: A-Ö',
    nameDesc: 'Namn: Ö-A',
    priceRange: 'Prisklass',
    under: 'Under',
    over: 'Över',
    quickPay: 'Snabbkassa',
    renovation: 'Renovering',
    installation: 'Installation',
    demolition: 'Rivning',
    cleaning: 'Städning',
    moving: 'Flytt',
    homeServiceSubcategories: 'Typ av hemmatjänst',
    carInspection: 'Besiktning',
    carRepair: 'Reparation',
    carMaintenance: 'Underhåll',
    carServiceSubcategories: 'Typ av biltjänst',
    homeRepair: 'Reparation',
    catering: 'Catering',
    wellness: 'Hälsa & Välmående',
    petServices: 'Husdjurstjänster',
    education: 'Utbildning',
    handymanServiceSubcategories: 'Typ av hantverkartjänst',
    handymanSmallRepairs: 'Småreparationer',
    handymanAssembly: 'Montering',
    handymanPainting: 'Målning',
    selectTimeFor: 'Välj tid för',
    noSlotsAvailable: 'Inga fler lediga tider idag.',
    slotSelected: 'Tid vald!',
    fullName: 'Fullständigt namn',
    email: 'E-postadress',
    phone: 'Telefonnummer',
    street: 'Gatuadress',
    city: 'Stad',
    postalCode: 'Postnummer',
    country: 'Land',
    cardholderName: 'Kortinnehavarens namn',
    cardNumber: 'Kortnummer',
    expiryDate: 'Giltighetsdatum (MM/ÅÅ)',
    cvc: 'CVC',
    fieldRequired: 'Detta fält är obligatoriskt',
    emailInvalid: 'Ange en giltig e-postadress',
    phoneInvalid: 'Ange ett giltigt telefonnummer',
    contactInfo: 'Kontaktuppgifter',
    stepCart: 'Varukorg',
    stepDelivery: 'Leverans',
    stepPayment: 'Betalning',
    stepConfirmation: 'Bekräftelse',
    showOrderSummary: 'Visa ordersammanfattning',
    hideOrderSummary: 'Dölj ordersammanfattning',
    flooring: 'Golvläggning',
    construction: 'Bygg',
    carpentry: 'Snickeri',
    countrySweden: 'Sverige',
    countryPakistan: 'Pakistan',
    selectCountry: 'Välj ett land...',
    whatsIncluded: 'Vad som ingår',
    duration: 'Varaktighet',
    hours: 'timmar',
    'I agree to the': 'Jag godkänner',
    'Terms & Conditions': 'användarvillkoren',
    termsContent: 'Användarvillkor: Detta är platshållarvillkor. I en riktig applikation skulle detta länka till en dedikerad sida med villkor.',
    'Pay Amount': 'Betala {amount}',
    scanWithSwish: 'Skanna med Swish-appen',
    swishNumber: 'Swish-nummer',
    amountToPay: 'Belopp att betala',
  },
};