import type { Item } from './types';

export const translations = {
  en: {
    title: 'Buzz',
    homeServices: 'Home Services',
    carServices: 'Car Services',
    rentalServices: 'Rental Services',
    hamtaServices: 'Pickup Services',
    vendingServices: 'Vending',
    parkingServices: 'Parking',
    handymanServices: 'Handyman',
    businessServices: 'For Business',
    addToCart: 'Add to Cart',
    addedToCart: 'Added!',
    cartTitle: 'Your Cart',
    cartEmpty: 'Your cart is empty.',
    subtotal: 'Subtotal',
    checkout: 'Checkout',
    bookingDateTime: 'Booking Details',
    selectDateTime: 'Please select a date and time for the service',
    close: 'Close',
    language: 'Language',
    location: 'Location',
    english: 'English',
    swedish: 'Swedish',
    sweden: 'Sweden (SEK)',
    pakistan: 'Pakistan (PKR)',
    searchPlaceholder: 'Search for services...',
    footerText: 'All rights reserved.',
    contactUs: 'Contact Us',
    address: 'Address',
    viewDetails: 'View Details',
    hideDetails: 'Hide Details',
    viewMoreDetails: 'View More Details',
    hideMoreDetails: 'Hide More Details',
    orderSuccessTitle: 'Order Placed!',
    orderSuccessMessage: 'Thank you for your order. Your order ID is',
    backToShopping: 'Back to Shopping',
    paymentMethod: 'Payment Method',
    cashOnDelivery: 'Cash on Delivery',
    swish: 'Swish',
    card: 'Credit/Debit Card',
    googlePay: 'Google Pay',
    applePay: 'Apple Pay',
    placeOrder: 'Place Order',
    continueToPayment: 'Continue to Payment',
    backToCart: 'Back to Cart',
    deliveryAddress: 'Delivery Address',
    paymentDetails: 'Payment Details',
    orderSummary: 'Order Summary',
    heroTitle: "Your Neighbourhood's On-Demand Service",
    heroSubtitle: 'Last-mile and on-demand services for your home and business. From home care to IT support, we are here to help.',
    browseServices: 'Browse Services',
    forBusinesses: 'For Businesses',
    item: 'item',
    items: 'items',
    ariaLabelLanguage: 'Select language',
    ariaLabelLocation: 'Select location',
    ariaLabelToggleDark: 'Switch to dark theme',
    ariaLabelToggleLight: 'Switch to light theme',
    ariaLabelOpenCart: 'Open cart',
    ariaLabelHomepage: 'Go to homepage',
    categories: 'Service categories',
    sort: 'Sort by',
    priceAsc: 'Price: Low to High',
    priceDesc: 'Price: High to Low',
    nameAsc: 'Name: A-Z',
    nameDesc: 'Name: Z-A',
    priceRange: 'Price Range',
    under: 'Under',
    over: 'Over',
    quickPay: 'Quick Pay',
    renovation: 'Renovation',
    installation: 'Installation',
    demolition: 'Demolition',
    cleaning: 'Cleaning',
    moving: 'Moving',
    homeServiceSubcategories: 'Home Service Type',
    carInspection: 'Inspection',
    carRepair: 'Repair',
    carMaintenance: 'Maintenance',
    carServiceSubcategories: 'Car Service Type',
    homeRepair: 'Repair',
    catering: 'Catering',
    wellness: 'Wellness',
    petServices: 'Pet Services',
    education: 'Education',
    handymanServiceSubcategories: 'Handyman Service Type',
    handymanSmallRepairs: 'Small Repairs',
    handymanAssembly: 'Assembly',
    handymanPainting: 'Painting',
    selectTimeFor: 'Select time for',
    noSlotsAvailable: 'No more slots available for today.',
    slotSelected: 'Slot selected!',
    fullName: 'Full Name',
    email: 'Email Address',
    phone: 'Phone Number',
    street: 'Street',
    city: 'City',
    postalCode: 'Postal Code',
    country: 'Country',
    cardholderName: 'Cardholder Name',
    cardNumber: 'Card Number',
    expiryDate: 'Expiry Date (MM/YY)',
    cvc: 'CVC',
    fieldRequired: 'This field is required',
    emailInvalid: 'Please enter a valid email address',
    phoneInvalid: 'Please enter a valid phone number',
    contactInfo: 'Contact Information',
    stepCart: 'Cart',
    stepDelivery: 'Delivery',
    stepPayment: 'Payment',
    stepConfirmation: 'Confirmation',
    showOrderSummary: 'Show Order Summary',
    hideOrderSummary: 'Hide Order Summary',
    flooring: 'Flooring',
    construction: 'Construction',
    carpentry: 'Carpentry',
    countrySweden: 'Sweden',
    countryPakistan: 'Pakistan',
    selectCountry: 'Select a country...',
    whatsIncluded: "What's Included",
    duration: "Duration",
    hours: "hours",
    'I agree to the': 'I agree to the',
    'Terms & Conditions': 'Terms & Conditions',
    termsContent: 'Terms and Conditions: These are placeholder terms. In a real application, this would link to a dedicated terms page.',
    'Pay Amount': 'Pay {amount}',
    scanWithSwish: 'Scan with Swish app',
    swishNumber: 'Swish Number',
    amountToPay: 'Amount to Pay',
    gardening: 'Gardening',
    seasonal: 'Seasonal',
    itSupport: 'IT Support',
  },
  sv: {
    title: 'Buzz',
    homeServices: 'Hemmatjänster',
    carServices: 'Biltjänster',
    rentalServices: 'Uthyrning',
    hamtaServices: 'Hämta-tjänster',
    vendingServices: 'Automater',
    parkingServices: 'Parkering',
    handymanServices: 'Hantverkare',
    businessServices: 'För Företag',
    addToCart: 'Lägg i varukorg',
    addedToCart: 'Tillagd!',
    cartTitle: 'Din varukorg',
    cartEmpty: 'Din varukorg är tom.',
    subtotal: 'Delsumma',
    checkout: 'Gå till kassan',
    bookingDateTime: 'Bokningsdetaljer',
    selectDateTime: 'Välj ett datum och en tid för tjänsten',
    close: 'Stäng',
    language: 'Språk',
    location: 'Plats',
    english: 'Engelska',
    swedish: 'Svenska',
    sweden: 'Sverige (SEK)',
    pakistan: 'Pakistan (PKR)',
    searchPlaceholder: 'Sök efter tjänster...',
    footerText: 'Alla rättigheter förbehållna.',
    contactUs: 'Kontakta oss',
    address: 'Adress',
    viewDetails: 'Visa detaljer',
    hideDetails: 'Dölj detaljer',
    viewMoreDetails: 'Visa mer information',
    hideMoreDetails: 'Dölj mer information',
    orderSuccessTitle: 'Beställning slutförd!',
    orderSuccessMessage: 'Tack för din beställning. Ditt order-ID är',
    backToShopping: 'Tillbaka till shopping',
    paymentMethod: 'Betalningsmetod',
    cashOnDelivery: 'Postförskott',
    swish: 'Swish',
    card: 'Kredit-/betalkort',
    googlePay: 'Google Pay',
    applePay: 'Apple Pay',
    placeOrder: 'Slutför beställning',
    continueToPayment: 'Fortsätt till betalning',
    backToCart: 'Tillbaka till varukorgen',
    deliveryAddress: 'Leveransadress',
    paymentDetails: 'Betalningsinformation',
    orderSummary: 'Ordersammanfattning',
    heroTitle: 'Ditt Grannskaps On-Demand Tjänst',
    heroSubtitle: 'Last-mile och on-demand-tjänster för ditt hem och företag. Från hemvård till IT-support, vi är här för att hjälpa till.',
    browseServices: 'Visa tjänster',
    forBusinesses: 'För Företag',
    item: 'artikel',
    items: 'artiklar',
    ariaLabelLanguage: 'Välj språk',
    ariaLabelLocation: 'Välj plats',
    ariaLabelToggleDark: 'Byt till mörkt tema',
    ariaLabelToggleLight: 'Byt till ljust tema',
    ariaLabelOpenCart: 'Öppna varukorg',
    ariaLabelHomepage: 'Gå till startsidan',
    categories: 'Tjänstekategorier',
    sort: 'Sortera efter',
    priceAsc: 'Pris: Lågt till Högt',
    priceDesc: 'Pris: Högt till Lågt',
    nameAsc: 'Namn: A-Ö',
    nameDesc: 'Namn: Ö-A',
    priceRange: 'Prisklass',
    under: 'Under',
    over: 'Över',
    quickPay: 'Snabbkassa',
    renovation: 'Renovering',
    installation: 'Installation',
    demolition: 'Rivning',
    cleaning: 'Städning',
    moving: 'Flytt',
    homeServiceSubcategories: 'Typ av hemmatjänst',
    carInspection: 'Besiktning',
    carRepair: 'Reparation',
    carMaintenance: 'Underhåll',
    carServiceSubcategories: 'Typ av biltjänst',
    homeRepair: 'Reparation',
    catering: 'Catering',
    wellness: 'Hälsa & Välmående',
    petServices: 'Husdjurstjänster',
    education: 'Utbildning',
    handymanServiceSubcategories: 'Typ av hantverkartjänst',
    handymanSmallRepairs: 'Småreparationer',
    handymanAssembly: 'Montering',
    handymanPainting: 'Målning',
    selectTimeFor: 'Välj tid för',
    noSlotsAvailable: 'Inga fler lediga tider idag.',
    slotSelected: 'Tid vald!',
    fullName: 'Fullständigt namn',
    email: 'E-postadress',
    phone: 'Telefonnummer',
    street: 'Gatuadress',
    city: 'Stad',
    postalCode: 'Postnummer',
    country: 'Land',
    cardholderName: 'Kortinnehavarens namn',
    cardNumber: 'Kortnummer',
    expiryDate: 'Giltighetsdatum (MM/ÅÅ)',
    cvc: 'CVC',
    fieldRequired: 'Detta fält är obligatoriskt',
    emailInvalid: 'Ange en giltig e-postadress',
    phoneInvalid: 'Ange ett giltigt telefonnummer',
    contactInfo: 'Kontaktuppgifter',
    stepCart: 'Varukorg',
    stepDelivery: 'Leverans',
    stepPayment: 'Betalning',
    stepConfirmation: 'Bekräftelse',
    showOrderSummary: 'Visa ordersammanfattning',
    hideOrderSummary: 'Dölj ordersammanfattning',
    flooring: 'Golvläggning',
    construction: 'Bygg',
    carpentry: 'Snickeri',
    countrySweden: 'Sverige',
    countryPakistan: 'Pakistan',
    selectCountry: 'Välj ett land...',
    whatsIncluded: 'Vad som ingår',
    duration: 'Varaktighet',
    hours: 'timmar',
    'I agree to the': 'Jag godkänner',
    'Terms & Conditions': 'användarvillkoren',
    termsContent: 'Användarvillkor: Detta är platshållarvillkor. I en riktig applikation skulle detta länka till en dedikerad sida med villkor.',
    'Pay Amount': 'Betala {amount}',
    scanWithSwish: 'Skanna med Swish-appen',
    swishNumber: 'Swish-nummer',
    amountToPay: 'Belopp att betala',
    gardening: 'Trädgårdsskötsel',
    seasonal: 'Säsong',
    itSupport: 'IT-Support',
  },
};